### PR TITLE
Fixed problem with incorrect display of messages in UTF-8 encoding

### PR DESCRIPTION
**Pull request by pacmastar**
Fixed problem with incorrect display of messages in UTF-8 encoding.
I guess this is due to the utf-8 encoding of the file messages_ru.properties

Before
getdown1
After
getdown2

### CODE REVIEW

**Comment by sergiorussia** [comment]
@pacmastar nice catch, totally forgot to enable transparent conversion (https://stackoverflow.com/a/9818962) in IDEA ) i think it's better to use ``native2ascii -encoding UTF-8 file file``. btw looks like ``it`` locale is broken as well

**Comment by samskivert** [comment]
I would rather we just properly encoded the _ru.properties files rather than change the way Getdown loads translation files. All of the other languages have been properly encoded, it would be weird extra complexity to have special handling for the Russian translations.

**Comment by samskivert** [comment]
I understand that it's annoying to edit the files once they've been translated from UTF8 to the escaped UTF8 format, so maybe I'll create a build step that does the proper conversion.

**Comment by samskivert** [comment]
OK, I modified the build to do the native2ascii conversion, so now we can keep all the translation files in UTF-8, which makes them a zillion times easier to read and edit. I've also un-converted all the old translation files so everything is now in UTF8.

**Pull request closed without merging**
