### PR TITLE
load bootstrap.properties from getdown-launcher.jar

### PR DESCRIPTION
**Pull request by vgropp**
Hi,

we need a as simple as possible bootstrap solution for our application. Therefor deploying a getdown-launcher.jar including a getdown.txt is a step to much for us and we don't have the possibility to deploy the first getdown-launcher.jar and txt otherwise.

I developed a simple solution to include a "bootstrap.properties" file in the getdown-launcher.jar so getdown will fetch the first getdown.txt in a (server-side) configurable appdir. There is an optional variable in the appdir property to reference the user home directory on the client.

I tried to be as less invasive as possible. Please feel free to comment and correct style and location. I hope there is a chance to merge this request somehow.

Volker

### CODE REVIEW

**Comment by samskivert** [comment]
I'm on board with this change. I like the idea of a custom-built getdown.jar that installs a single application into a preconfigured directory without any additional supporting files. It would allow a user to download a single jar file and "run it" (assuming such a thing remains possible in the future).

I have a few questions/comments:

1. This only appears to configure the appdir (the directory on the user's local machine in which to host the application). For a truly standalone jar, the appbase (URL) would also need to be specified. Am I missing something with regard to your needs, or has this been overlooked?

2. I would like to use the new Build.java mechanism instead of a separate bootstrap.properties file. If you have seen the recent URL whitelist support, this demonstrates how this would work. You would pass a system property to Maven when running the build, like:

```
mvn package -Dgetdown.bootstrap.appdir='${user.home}/foo'
```

and it would bake the requested bootstrap appdir into the built jar file. No additional `.properties` files would be used or needed.

3. I would like to provide support for a "smarter" appdir selection, perhaps something like `getdown.bootstrap.appname` where Getdown would install the application in the OS-appropriate directory using the supplied app name (`${HOME}/AppData/${appname}` on Windows, `~/Library/Application Data/${appname}` on macOS, `~/.getdown/${appname}` on Linux). We could also support a OS-agnostic approach that supported `${user.home}` variable substitution, but I feel that that would be somewhat hostile to multiple operating systems. I suppose someone may only be using Getdown to deploy to a very specific target environment on a single OS, so such a mechanism would be valuable.

4. In the interest of security, I would prefer that this mechanism override anything supplied on the command line. So the `appname` / `appdir` configuration would take precedence over one specified on the command line (and thus probably not be named `bootstrap` because it wouldn't be a bootstrap mechanism, just a different way to provide that configuration). The `appbase` configuration _would_ be a bootstrap value because it would download the `getdown.txt` from that location initially, but henceforth would use the appbase specified in the downloaded `getdown.txt` file once it exists.

Anyhow, if these changes still meet your needs, I'd be happy to implement them. Let me know what you think.

**Comment by samskivert** [comment]
Also, I will probably add a mechanism to the Getdown build to supply these build-time configurations via a local `build.properties` file. This will allow the properties to be supplied at build time either via command line arguments to Maven, or via this build.properties file. Depending on ones own build environment, a properties file may be easier or preferable than passing custom arguments to Maven.

**Comment by vgropp** [comment]
Hi,

the appbase is included into the properties as well. I did not mention we have multiple installations, so configuration at build time is not an option. I have written a simple servlet that adds the bootstrap.properties to the jar on every request. I am sure on large installations with thousands of requests this is not an option. But we have only a few client on every host.

Völker

**Comment by samskivert** [comment]
Ah, I glossed over the couple of lines setting the appbase and forgot that Getdown already handled having the appbase set as a system property.

Well, fair enough re: your requirements to inject a bootstrap.properties into a jar file as its being served. That's certainly an added flexibility of using a .properties file. I'm OK with that.

I may still add additional support for baked in properties and the `appname` mechanism that I described. I feel like this is a good idea and would like to make it a flexible "full-fledged" feature.

**Comment by vgropp** [comment]
It is probably still missing in the wiki. On first glance i do not see any good page to describe this little feature

**Pull request merged**
