### PR TITLE
Git ignore Maven and Eclipse local build artifacts

### PR DESCRIPTION
**Pull request by sdgx**

### CODE REVIEW

**Comment by samskivert** [comment]
I prefer that people who use particular IDEs add their preferred IDE's metadata files to their own global .gitignore. The alternative would be that every project had to contain the union of all possible metadata files generated by all possible IDEs used by anyone on that project. Seems like 1x1 is better than NxM.

**Comment by sdgx** [comment]
No problem. What about the "target" directories, which are generated by Maven? Since it's the default build system, I assume they will affect every contributor.

**Comment by samskivert** [comment]
Yeah, that was already being ignored when the only target directory was at the top level, I've fixed it to cope with the fact that they're in the submodule directories now.

**Comment by sdgx** [comment]
Great, thanks!

**Pull request closed without merging**
