### PR TITLE
Proxy Authentification

### PR DESCRIPTION
**Pull request by ThomasG-AI**
Hi there,

we added support for Proxy Authentification to getdown. We mainly changed 3 things:

1. We are using the java.net.Proxy class for proxy settings in the URLConnections. This is because if you set it only as SystemProperty, it seems java uses a fallback if the proxy is not reachable and tries to connect without proxy. Which we think is not desirable. 
2. We changed the Proxy dialog to include 2 fields with username and password and a checkbox field to activate the 2 input fields. Also we changed some minor locales in the dialog.
3. Since it is not very secure to set the credentials as SystemProperty to pass trough to the main application that gets started, we included a Service Provider Interface. One method for saving the credentials and one for loading the credentials. With this way everyone who uses getdown can implement there own secure way of passing the credentials to the application that gets started. If no SPI is implemented, the credentials will only be set in getdown.

Greetings
ThomasG

### CODE REVIEW

**Comment by samskivert** [comment]
Unfortunately this PR seems to contain a tremendous number of changes unrelated to adding the new proxy authentication feature. A ton of code has been either rearranged, reformatted, or erroneously reverted to much older versions (it seems that maybe the UpdateInterface class was removed?).

I'm afraid I can't merge it until it has been redone to actually only change the code necessary to add the proxy authentication feature, and to ideally make minimal or no other changes to the code other than those needed for the new feature.

**Comment by samskivert** [comment]
If you look at this complete diff, you can see a ton of changes to the Application class and more:

https://github.com/threerings/getdown/pull/175/files

**Comment by ThomasG-AI** [comment]
Would it be possible that you provide us with your format settings file? That would make our lives way easier to reformat the code without being at risk breaking something

**Comment by ThomasG-AI** [comment]
Is there any way to make your life easier to view the changes? We resolved some merge issues already and removed some unnecessary code changes.

If you provide us with your formatting settings we could at least format the code right.

**Comment by samskivert** [comment]
I don't have a formatting settings file. You can look at the diff and see hundreds of lines of formatting changes unrelated to this PR. Look at the diffs for `Getdown.java`, all those hundreds of lines of changes should not be there. It is not difficult to inspect the diff to see the obvious mismatches: wrong number of spaces for indent, wrong cuddling of curly brackets, etc.

I don't mean to be a jerk, but I'm not going to hold your hand through this completely trivial fix to a problem with your pull request that should have never existed in the first place. A professional engineer can easily understand and match the style of a body of code to which they are contributing. If you cannot even perform this basic syntactic process, how can I have any faith that the actual semantic changes you are proposing are not full of bugs?

Indeed, just looking at the code I spotted a regression in that https proxies are no longer handled properly.

I'm not trying to be combative or to prevent you from getting this feature into Getdown. It's a reasonable feature (though the SPI addition is of questionable value, in my opinion). But I'm not going to merge a pull request that has blatant disregard for the organization and style of all of the existing code, and I don't particularly want to waste my time holding your hand through the process of cleaning up your changes so that they can even be reviewed for correctness without having to wade through hundreds of unrelated diffs.

I would expect better from a second year college intern, to be quite frank.

**Comment by samskivert** [comment]
OK, I have adapted and cleaned up the remainder of your PR and committed proxy auth support to the main branch.

Without a mechanism for saving the credentials supplied by the user, this seems like a very annoying feature. Unless the app is using managed versioning, Getdown will request the proxy credentials every single time it runs, which seems rather annoying.

In any case, the feature is merged. Thanks again for taking the time to clean it up enough so that I could actually understand what it was doing.

**Pull request closed without merging**
