### PR TITLE
revert processArg for appbase

### PR DESCRIPTION
**Pull request by sergiorussia**
that change broke versioned app update entirely. pls publish new getdown asap

### CODE REVIEW

**Comment by sergiorussia** [comment]
temporary workaround for app authors:
make symbolic link from old affected version to the latest like this

eg before
```
drwxrwsr-x version1 # with broken getdown
drwxrwsr-x version2
drwxrwsr-x versionLatest
```

after
```
lrwxrwxrwx version1 -> versionLatest
lrwxrwxrwx version2 -> versionLatest
drwxrwsr-x versionLatest
```

**Comment by samskivert** [comment]
Uh oh. Thanks for catching this. I'll publish a new release presently and then look into what's going wrong.

**Comment by samskivert** [comment]
1.8.6 is making its way to Maven Central now. I'm going to write some tests to cover some of this Application init stuff and then I'll do some hackery to reinstate the ability to processArg() appbase without breaking versioning.

**Comment by sergiorussia** [comment]
thanks. btw can you pls fix missing patch handling? annoying error as getdown does not check if patch present or not, spamming logs with looong file not found errors with stack traces etc etc

**Comment by samskivert** [comment]
Hopefully e7818030a7181681b7c2a3395810b5ce510eda96 will make things better.

**Comment by neuweiler** [comment]
My sincere apologies for causing so much trouble! I hope you and the app devs discovered it before any customers were affected! I was still investigating bootstrapping into an empty directory and integrating getdown with maven so that I didn't test a version upgrade. If @samskivert wants me to give it another try, I'll redo the change but this time correctly and with extensive testing.

**Comment by sergiorussia** [comment]
@neuweiler no worries, workaround with symbolic links worked fine despite a lot of users were affected. @samskivert already fixed your change in e376dff. unit tests to the rescue :wink:

**Pull request merged**
