### PR TITLE
Avoid corrupted resources when download is interrupted

### PR DESCRIPTION
**Pull request by runiter**
1) Download resources first into a temporary file
2) Perform verification and digest comparison with the downloaded
temporary file instead of the original if temporary file exist
3) Only when verification completes successfully rename all the
temporary files to override the original. This step can be done
automatically or manually by calling GetDown.install() which is useful
for those who want to download in background and install upon program
exit.

### CODE REVIEW

**Comment by runiter** [comment]
When will you pull these changes into the main git repository?

**Comment by samskivert** [comment]
I just did, but now it seems like they've broken things. My testapp no longer works.

**Comment by samskivert** [comment]
Oh wait, maybe I broke everything. :)

**Comment by runiter** [comment]
Which test fails? maybe I can help determine if it's due to my changes

**Comment by samskivert** [comment]
It was related to some other changes I had merged in before. It's all good now, all the new stuff is in and working. Woo!

**Comment by runiter** [comment]
Awesome, thanks!

**Pull request merged**
